[tools]
"cargo:sbyte" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-cache" = "latest"
"pipx:SuperClaude" = "latest"
"npm:md-to-pdf" = "latest"
"npm:github-markdown-css" = "latest"
"npm:vite" = "latest"
"github:melkeydev/go-blueprint" = "latest"
"github:h0rv/d2-mcp" = "latest"
"npm:@mixedbread/mgrep" = "latest"
"github:jdx/fnox" = "latest"
"github:jdx/usage" = "latest"
"cargo:krokiet" = "latest"
"github:JohnnyMorganz/StyLua" = "latest"
"github:sharkdp/fd" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:noborus/ov" = "latest"
"github:sharkdp/pastel" = "latest"
"github:neilotoole/sq" = "latest"
"github:sxyazi/yazi" = "latest"
"github:ajeetdsouza/zoxide" = "latest"
"github:o2sh/onefetch" = "latest"
"github:Slackadays/Clipboard" = "latest"
"github:bee-san/RustScan" = "latest"
"github:astral-sh/ruff" = "latest"
go = "latest"
"npm:skills" = "latest"
"nix:bun" = "latest"
"nix:hello" = "latest"

[settings]
experimental = true
quiet = true
