[tools]
"cargo:sbyte" = "latest"
"cargo:cargo-update" = "latest"
"pipx:ruff" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"cargo:cargo-cache" = "latest"
"pipx:meson" = "latest"
"pipx:ninja" = "latest"
"pipx:SuperClaude" = "latest"
"npm:md-to-pdf" = "latest"
"npm:github-markdown-css" = "latest"
"npm:nuekit" = "latest"
"npm:vite" = "latest"
"go:github.com/nizos/tdd-guard/reporters/go/cmd/tdd-guard-go" = "v0.2.1"
"npm:@opentui/core" = "latest"
"npm:@opentui/react" = "latest"
"go:github.com/wailsapp/wails/v3/cmd/wails3" = "latest"
"github:melkeydev/go-blueprint" = "latest"
"github:h0rv/d2-mcp" = "latest"
"npm:@mixedbread/mgrep" = "latest"
"nix:nodejs" = "latest"
"nix:rustup" = "latest"
"nix:ruby" = "latest"
"github:jdx/fnox" = "latest"
"github:jdx/usage" = "latest"
"nix:bun" = "latest"
"nix:uv" = "latest"

[settings]
experimental = true
quiet = true

[env]

